<#
.SYNOPSIS
  Office 365 Add user to distribution group
.DESCRIPTION
  This script will add a user to a distribution group.
  This script uses the session that is generated by the o365.ps1 script
.PARAMETER
  None at this time
.INPUTS
  Requires the session generated by the o365.ps1 script
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  09/12/2019
  Modified Date:  11/01/2019
  Purpose/Change: Added description
.EXAMPLE
  ".\o365CreateUser.ps1"
#>
Write-Host "
Distribution Groups
-------------------"
(Get-DistributionGroup).DisplayName | Sort
Write-Host "-------------------
"
$group = Read-Host -Prompt 'Group to add user to: '
Write-Host "
       Users
-------------------"
(Get-MsolUser -All | Where {$_.isLicensed -eq $true}).UserPrincipalName | Sort
Write-Host "-------------------
"
$user = Read-Host -Prompt 'User to add to the distribution group: '
Add-DistributionGroupMember -Identity $group -Member $user -Confirm:$false
Write-Host "Added $user to the $group distribution group."
Remove-Variable -Name user,group