<#
.SYNOPSIS
  Office 365 Generate List of Users in Distribution Lists
.DESCRIPTION
  This script will Generate a List of all distribution groups and the users in them
.PARAMETER
  None at this time
.INPUTS
  Open o365 session generated by o365.ps1
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  09/12/2019
  Modified Date:  11/01/2019
  Purpose/Change: Added description
.EXAMPLE
  ".\o365UsersInDistributionLists.ps1"
#>
$groups = Get-DistributionGroup
ForEach ($group in $groups)
    {
    Write-Host " "
    Write-Host $group.DisplayName
    Write-Host '-------------------------'
    (Get-DistributionGroupMember -Identity $group.Name).Name
    }