<#
.SYNOPSIS
  Office 365 Set Auto Reply
.DESCRIPTION
  This script will set an autoreply for the user
.PARAMETER
  None at this time
.INPUTS
  Open o365 session generated by o365.ps1
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  11/15/2019
  Modified Date:  
  Purpose/Change: 
.EXAMPLE
  ".\o365AutoReply.ps1"
#>
Write-Host "
       Users
-------------------"
(Get-MsolUser -All).UserPrincipalName | Sort
Write-Host "-------------------
"
$user = Read-Host "Email address of the auto reply to be set on"
$message = Read-Host "Auto Reply message"
Set-MailboxAutoReplyConfiguration -Identity $user -AutoReplyState Enabled -ExternalMessage $message -InternalMessage $message -Confirm
Write-Host "The $user account has been set with the following away message:
$message"

Remove-Variable user,message