<#
.SYNOPSIS
  Office 365 Reset User Password
.DESCRIPTION
  This script will reset a password for an Office 365 User
.PARAMETER
  None at this time
.INPUTS
  Open o365 session generated by o365.ps1
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  09/12/2019
  Modified Date:  11/01/2019
  Purpose/Change: Added description
.EXAMPLE
  ".\o365ResetUserPassword.ps1"
#>
Write-Host "
       Users
-------------------"
(Get-MsolUser -All | Where {$_.isLicensed -eq $true}).UserPrincipalName | Sort
Write-Host "-------------------
"
$user = Read-Host "Email address to reset password: "
$password = Read-Host "Enter new password: "
Set-MsolUserPassword -UserPrincipalName $user -NewPassword $password
Write-Host "
I reset to password for $user to $password
"
Remove-Variable user,password