<#
.SYNOPSIS
  Office 365 Add user to shared mailbox
.DESCRIPTION
  This script will add a user to a shared mailbox
.PARAMETER
  None at this time
.INPUTS
  Requires msol session generated by the o365.ps1 script
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  11/04/2019
  Modified Date:  
  Purpose/Change:
  
.EXAMPLE
  ".\o365AddUserToSharedMailbox.ps1"
#>
Write-Host "
       Users
-------------------"
(Get-MsolUser -All | Where {$_.isLicensed -eq $true}).UserPrincipalName | Sort
Write-Host "-------------------
"
$user = Read-Host "User to add to shared mailbox"
Write-Host "
 Shared Mailbox's
-------------------"
(Get-Mailbox -Filter {recipienttypedetails -eq "SharedMailbox"}).Alias
Write-Host "-------------------
"
$shared = Read-Host "Shared mailbox to add to $user"

Add-MailboxPermission $shared -User $user -AccessRights FullAccess -InheritanceType all

Write-Host  (Get-Mailbox $shared | ForEach {Get-MailboxPermission -Identity $_.Alias | Format-Table user})

Write-Host "I added $user to the $shared shared mailbox."

Remove-Variable user,shared