<#
.SYNOPSIS
  Office 365 Delegate account to user
.DESCRIPTION
  This script will Delegate a Office 365 account to a user
.PARAMETER
  None at this time
.INPUTS
  Requires msol session generated by the o365.ps1 script
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  11/04/2019
  Modified Date:  
  Purpose/Change:
  
.EXAMPLE
  ".\o365DelegateAccountToUser.ps1"
#>
# List all Users
Write-Host "
       Users
-------------------"
(Get-MsolUser -All | Where {$_.isLicensed -eq $true}).UserPrincipalName | Sort
Write-Host "-------------------
"
$source = Read-Host "Account to be delegated from"
$target = Read-Host "Account to be delegated to"


Remove-Variable sorce,target