<#
.SYNOPSIS
  Office 365 Deactivated User
.DESCRIPTION
  This script will deactivate a o365 user using the session connected by o365.ps1 script.
.PARAMETER
  None at this time
.INPUTS
  Requires the o365 session generated by the o365.ps1 script
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  09/12/2019
  Modified Date:  11/01/2019
  Purpose/Change: Added description to script
.EXAMPLE
  ".\o365DeactivateUser.ps1"
#>

# List all Users
Write-Host "
       Users
-------------------"
(Get-MsolUser -All | Where {$_.isLicensed -eq $true}).UserPrincipalName | Sort
Write-Host "-------------------
"
# Get user to deactivate
$user = Read-Host -Prompt 'User to deactivate: '
# Get user to foward
$fwd = Read-Host -Prompt 'User to forward to (Leave Blank for None): '
# Remove user from all distribution groups
$groups = Get-DistributionGroup
ForEach ($group in $groups)
    {
    $names = (Get-DistributionGroupMember -Identity $group.Name).Name
    if ($user -in $names)
        {
        Remove-DistributionGroupMember -Identity $group.DisplayName -Member $user -Confirm:$false -Verbose
        Write-Host "Removed $user from "$group.DisplayName
        }
    }
# Set mailbox to shared
Set-Mailbox $user -Type Shared -Verbose
# Remove all licenses assigned to user
$licenses = ((Get-MsolUser -UserPrincipalName $user).licenses).AccountSkuId
ForEach ($license in $licenses)
    {
    Set-MsolUserLicense -UserPrincipalName $user -RemoveLicenses $license -Verbose
    Write-Host "Removed the $license license from $user"
    }
# Block account from SignIn and forward
Set-AzureADUser -ObjectId $user -AccountEnabled $false -Verbose
if ($fwd)
    {
    Set-Mailbox -Identity $user -DeliverToMailboxAndForward $true -ForwardingAddress $fwd -Verbose
    Write-Host "The $user mailbox is now being forwarded to $fwd"
    }
Set-Mailbox -Identity $user -HiddenFromAddressListsEnabled $true -Verbose
Write-Host "I disabled the $user account."
Remove-Variable user,license,licenses,group,groups,fwd