<#
.SYNOPSIS
  Office 365 Add Alias to user
.DESCRIPTION
  This script will add an alias to a user account
  This script uses the session that is generated by the o365.ps1 script
.PARAMETER
  None at this time
.INPUTS
  Requires the session generated by the o365.ps1 script
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  11/05/2019
  Modified Date:  
  Purpose/Change: Added description
.EXAMPLE
  ".\o365AddAliasToUser.ps1"
#>

"      Users
-------------------"
(Get-MsolUser -All | Where {$_.isLicensed -eq $true}).UserPrincipalName | Sort
Write-Host "-------------------
"
$user = Read-Host -Prompt 'User to add alias to'
$alias = Read-Host -Prompt "Alias to add to $user (eg.Alias@domain.com)"
Set-Mailbox $user -EmailAddresses @{Add=$alias}
Write-Host "I added the $alias alias to $user
"
Get-Mailbox $user | Select-Object DisplayName,@{Name=“EmailAddresses”;Expression={$_.EmailAddresses |Where-Object {$_ -LIKE “SMTP:*”}}} | Sort | Format-List
Remove-Variable -Name user,alias