<#
.SYNOPSIS
  Office 365 Remove User from all distribution lists
.DESCRIPTION
  This script will remove a user from all distribution groups.
.PARAMETER
  None at this time
.INPUTS
  Open o365 session generated by o365.ps1
.OUTPUTS
  None at this time
.NOTES
  Version:        1.0
  Author:         Ryan Bowen
  Company:        MedX Solutions
  Creation Date:  09/12/2019
  Modified Date:  11/01/2019
  Purpose/Change: Added description
.EXAMPLE
  ".\o365RemoveUserFromAllDistributionList.ps1"
#>
Write-Host "
       Users
-------------------"
(Get-MsolUser -All).UserPrincipalName | Sort
Write-Host "-------------------
"
$user = Read-Host -Prompt 'User to remove from distribution lists: '
$groups = Get-DistributionGroup
ForEach ($group in $groups)
    {
    $names = (Get-DistributionGroupMember -Identity $group.Name).Name
    if ($user -match $names)
        {
        Remove-DistributionGroupMember -Identity $group.DisplayName -Member $user
        Write-Host "Removed user from "$group.DisplayName
        }
    }
Remove-Variable user,groups,group,names